service:
  name: interview-test

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  # Environment variables for all functions in this service
  environment:
    NODE_ENV: ${opt:nodeEnv, self:provider.stage}
    MYSQL_HOST: '34.201.12.7'
    MYSQL_DATABASE: ${ssm:MYSQL_DATABASE}
    MYSQL_USER: ${ssm:MYSQL_USER}
    MYSQL_PASSWORD: ${ssm:MYSQL_PASSWORD}
    MYSQL_PORT: ${ssm:MYSQL_PORT}
    # Add environment variables here such as mysql connection information, elasticsearch connection information, etc.

functions:
  getStates:
    handler: handler.getStates
    name: getStates
    events:
    - http:
        path: states
        method: get
        cors: true
  getEmployees:
    handler: handler.getEmployees
    name: getEmployees
    events:
    - http:
        path: employees
        method: get
        cors: true
  postEmployee:
    handler: handler.postEmployee
    name: postEmployee
    events:
    - http:
        path: employees
        method: post
        cors: true
  patchEmployee:
    handler: handler.patchEmployee
    name: patchEmployee
    events:
    - http:
        path: employees/{id}
        method: patch
        cors: true
  deleteEmployee:
    handler: handler.deleteEmployee
    name: deleteEmployee
    events:
    - http:
        path: employees/{id}
        method: delete
        cors: true
