service:
  name: interview-test

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: local
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  # Environment variables for all functions in this service
  environment:
    NODE_ENV: ${opt:nodeEnv, self:provider.stage}
    # Add environment variables here such as mysql connection information, elasticsearch connection information, etc.

functions:
  helloGet:
    handler: handler.helloGet # Hint: Observe the way the exports work in each of the {folder}/index.ts files
    name: helloGet
    events:
    - http:
        path: hello
        method: get
    environment:
      # You can use function specific environment variables here (not required)
